### ISSUE TITLE
Remove Social location OARS tag

### ISSUE THREAD

**Issue by danirabbit** [ryonakano/atlas#12]
https://github.com/ryonakano/atlas/blob/a648883db82d67dfb57eae21811435ad04c35b99/data/com.github.ryonakano.atlas.appdata.xml.in#L27

OARS defines this as sharing your physical location with _other users_ and notes that "This does not include heuristic based location services, e.g. GeoIP and others."

So I don't think this tag applies in this case for maps

**Comment by ryonakano** [comment]
Oh, I overlooked that sentence. Thank you for your info :heart:
